/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CoordinatorAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JPanel;

/**
 *
 * @author suoxiyue
 */
public class CoordinatorAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel container;
    Enterprise enterprise;
    UserAccount userAccount;
    Network network;
    Organization organization;
    EcoSystem system;
    /**
     * Creates new form CoordinatorAdminWorkAreaJPanel
     */
    public CoordinatorAdminWorkAreaJPanel(JPanel container, Enterprise enterprise, 
                                    UserAccount ua, Network network, Organization org, EcoSystem system) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.userAccount = ua;
        this.network = network;
        this.organization = org;
        this.system = system;
        System.out.println("network size in current network = " + system.getNetworkList().size());
        
        for (Network n : system.getNetworkList()) {
            System.out.println(n.getName());
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                System.out.println(e.getName());
            }
        }
        //System.out.println("enterprise size in current network :" + network.getEnterpriseDirectory().getEnterpriseList().size());
        
        valueLabel.setText(userAccount.getEmployee().getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNewReportedCases = new javax.swing.JButton();
        btnViewAllAnimals = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();

        jLabel1.setText("Hello,");

        jLabel2.setText("Role: Coordinator Administrator");

        btnNewReportedCases.setText("New Reported Cases");
        btnNewReportedCases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewReportedCasesActionPerformed(evt);
            }
        });

        btnViewAllAnimals.setText("View All Animals");
        btnViewAllAnimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllAnimalsActionPerformed(evt);
            }
        });

        valueLabel.setText("<CoordinatorAdmin>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnViewAllAnimals))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnNewReportedCases))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(btnNewReportedCases)
                .addGap(36, 36, 36)
                .addComponent(btnViewAllAnimals)
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewReportedCasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewReportedCasesActionPerformed
        // TODO add your handling code here:
        NewReportedCasesJPanel jp = new NewReportedCasesJPanel(container, enterprise, organization, system);
        container.add("NewReportedCasesJPanel",jp);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnNewReportedCasesActionPerformed

    private void btnViewAllAnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllAnimalsActionPerformed
        // TODO add your handling code here:
        ViewAllAnimals jp = new ViewAllAnimals(container);
        container.add("ViewAllAnimals",jp);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnViewAllAnimalsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewReportedCases;
    private javax.swing.JButton btnViewAllAnimals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
