/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author suoxiyue
 */
public class HospitalAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel container;
    Enterprise enterprise;
    UserAccount userAccount;
    Network network;
    Organization organization;
    EcoSystem system;
    /**
     * Creates new form RandomReporterWorkAreaJPanel
     */
    public HospitalAdminWorkAreaJPanel(JPanel container, Enterprise enterprise, 
                                    UserAccount ua, Network network, Organization org, EcoSystem system) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.userAccount = ua;
        this.network = network;
        this.organization = org;
        this.system = system;
        
        valueLabel.setText(ua.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnManageVets = new javax.swing.JButton();
        btnProcessRequests = new javax.swing.JButton();
        btnAssignTasks = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();

        jLabel5.setText("Hello,");

        jLabel6.setText("Role: Hospital Administrator");

        btnManageVets.setText("Manage Vets");
        btnManageVets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVetsActionPerformed(evt);
            }
        });

        btnProcessRequests.setText("Process Cases");
        btnProcessRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestsActionPerformed(evt);
            }
        });

        btnAssignTasks.setText("Assign Tasks");
        btnAssignTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTasksActionPerformed(evt);
            }
        });

        valueLabel.setText("<Hospital Admin>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAssignTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnProcessRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManageVets, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addComponent(btnProcessRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAssignTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageVets, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTasksActionPerformed
        // TODO add your handling code here:
        AssignTaskToVetJPanel jp = new AssignTaskToVetJPanel(container,organization, userAccount);
        container.add("AssignTaskFromCoordJPanel", jp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnAssignTasksActionPerformed

    private void btnProcessRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestsActionPerformed
        // TODO add your handling code here:
        ProcessCases jp = new ProcessCases(container, userAccount);
        container.add("ProcessRequestFromVet", jp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnProcessRequestsActionPerformed

    private void btnManageVetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVetsActionPerformed
        // TODO add your handling code here:
        ManageVetJPanel jp = new ManageVetJPanel(container, organization);
        container.add("ManageVetJPanel", jp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnManageVetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignTasks;
    private javax.swing.JButton btnManageVets;
    private javax.swing.JButton btnProcessRequests;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
